pluginManagement {
    repositories {
        gradlePluginPortal()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

includeBuild 'libs/MiddleKeyPing'

includeBuild 'libs/WenyanNature'
// git update-index --assume-unchanged settings.gradle
// includeBuild(file('libs/WenyanNature').toPath().toRealPath().toAbsolutePath().toString())